function randomIntFromInterval(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'store',
      [
        {
          id: 1,
          user_id: 1,
          store_name: '9와 3/4번지 피자',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '남산 공원 근처에 위치한 이탈리안 피자집입니다. 나폴리 스타일의 화덕피자를 굽는 집으로 매장에 오시면 화덕을 직접 구경하실 수 있습니다. 대표메뉴로는 불고기 피자와 베지터리언 손님분들이 식사 가능한 베지터블 피자가 있습니다',
          store_address: '서울특별시 용산구 용산2가동 남산공원길 105 7층',
          store_category: '양식',
          store_lat: 37.550976488284654,
          store_lng: 126.99095582962613,
          business_hour: '11:00 ~ 23:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          user_id: 2,
          store_name: '샐러디',
          store_image: 'client/src/img/dummy/store1.png',
          store_order_quantity: '7',
          store_description:
            '강북에 8개의 매장을 갖추고 있는 샐러드 체인점입니다. 가장 유명한 메뉴는 아보카도 샐러드 입니다. 아보카도가 큼직하게 올라갔고, 병아리 콩과 각종 채소, 퀴노아까지 들어가있어 다이어트를 하셔서 식단 조절을 하셔야 하는 분들도 긴 포만감을 느끼실 수 있을겁니다',
          store_address: '서울특별시 마포구 합정동 396-14',
          store_category: '양식',
          store_lat: 37.543709,
          store_lng: 126.904409,
          business_hour: '11:30 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          user_id: 3,
          store_name: '한잔할래',
          store_image: 'client/src/img/dummy/store2.png',
          store_order_quantity: '10',
          store_description:
            '소주 한잔과 함께할 수 있는 음식을 팔고 있는 한잔할래 입니다. 골뱅이 비빔면, 감자탕 등 안주용으로 먹을 수 있는 다양한 음식들이 준비되어 있으니 친구 분들과 함께 방문하셔서 즐겨보세요~',
          store_address: '서울특별시 종로구 사직동 효자로 37',
          store_category: '한식',
          store_lat: 37.577698,
          store_lng: 126.976881,
          business_hour: '10:00 ~ 23:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          user_id: 4,
          store_name: '떡볶이 묵을래?',
          store_image: 'client/src/img/dummy/store4.png',
          store_order_quantity: '17',
          store_description:
            '가성비 갑!!!! 코드여고 앞에서 20년간 자리를 지켜온 식당입니다.저렴한 가격에 김밥과 비빔밥 등 간단한 음식들을 즐길 수 있습니다. 대표 메뉴로는 매운 불닭 돈까스가 있습니다. 이 메뉴를 10분 안에 드시는 분께는 비빔밥 한그릇을 다음 방문 때 무료로 제공해드립니다.',
          store_address: '서울특별시 서초구 서초동 서운로 133 2층',
          store_category: '분식',
          store_lat: 37.496511,
          store_lng: 127.02483,
          business_hour: '10:00 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          user_id: 5,
          store_name: 'K-타운',
          store_image: 'client/src/img/dummy/store5.png',
          store_order_quantity: '30',
          store_description:
            '뭐니뭐니 해도 한식이 최고!! BTS의 인기에 힘입어 많은 외국인 손님들께서 방문해주고 계십니다.',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '한식',
          store_lat: 37.555388,
          store_lng: 126.970782,
          business_hour: '11:30 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          user_id: 6,
          store_name: '프랑스파슷하',
          store_image: 'client/src/img/찌개.png',
          store_order_quantity: '5',
          store_description:
            '다채로운 생면 파스타의 세계에 오신 걸 환영합니다! 이탈리아 요리학교를 수료하고 미슐랭 3스타 레스토랑에서 경험을 쌓고오신 임현성 쉐프님께서 직접 만드신 파스타를 즐기실 수 있습니다. 현장방문은 이용이 힘드시고, 최소 3일전에 전화로 예약을 해주셔야 저희 레스토랑 음식들을 즐기실 수 있습니다. 불편을 드려 죄송합니다.',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '양식',
          store_lat: 37.559498,
          store_lng: 126.973151,
          business_hour: '11:30 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          user_id: 7,
          store_name: '버거401',
          store_image: 'client/src/img/찌개.png',
          store_order_quantity: '14',
          store_description:
            '요즘에 흔한 프랜차이즈와는 다릅니다!! 원산지표시는 확실하게 가게 내에 표시해놓고 있습니다. 걱정하지 마시고 와서 수제버거를 즐겨보세요!!',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '패스트푸드',
          store_lat: 37.50393,
          store_lng: 127.009644,
          business_hour: '11:30 ~ 16:30',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 8,
          user_id: 8,
          store_name: '앳하노이',
          store_image: 'client/src/img/찌개.png',
          store_order_quantity: '24',
          store_description:
            '베트남에서 온 요리사가 직접 만들어주는 베트남 쌀국수와 가정식을 즐겨보세요!! 대표 메뉴로는 양지 쌀국수와 스프링롤, 소프트크랩 튀김 등이 있습니다.',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '한식',
          store_lat: 37.506462,
          store_lng: 126.963802,
          business_hour: '11:00 ~ 20:30',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 9,
          user_id: 9,
          store_name: '덕수궁',
          store_image: 'client/src/img/찌개.png',
          store_order_quantity: '8',
          store_description:
            '이태원에서 인기를 끌었던 덕수궁이 이전했습니다!! 올해 초복은 7월 11일 일요일, 중복은 7월 21일 수요일, 말복은 8월 10일 화요일인데요. 더운 여름 복날에 삼계탕으로 몸보신하러 많이많이 찾아주세요~',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '한식',
          store_lat: 37.555893,
          store_lng: 127.04148,
          business_hour: '11:00 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 10,
          user_id: 10,
          store_name: '크리스마스엔',
          store_image: 'client/src/img/찌개.png',
          store_order_quantity: '15',
          store_description:
            '최근 슬기로운 코딩생활 드라마에 나오는 맛집입니다. 트러플 뇨끼와 양고기 스테이크가 대표 메뉴입니다',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '양식',
          store_lat: 37.529628,
          store_lng: 126.967185,
          business_hour: '10:30 ~ 20:30',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 11,
          user_id: 11,
          store_name: '옛날 할무니 짜장',
          store_image: 'client/src/img/찌개.png',
          store_order_quantity: '8',
          store_description:
            '인기에 힘입어 리모델링을 하며 홍콩감성으로 돌아왔습니다!! 최근 tv 예능 프로그램 자면 뭐하니에도 출연하여 큰 화제가 되었었습니다. 1980년대 홍콩 영화를 모티브로 한 인테리어와 함꼐 맛있는 중식을 즐겨보세요. 음식을 먹고 인증샷을 찍어 인스타그램에 태그와 함께 올려주신 분에게는 추첨을 통해 탕수육 공짜 쿠폰을 보내드립니다. 많은 관심 부탁드립니다!!',
          store_address: '서울특별시 중구 남대문로5가 581',
          store_category: '양식',
          store_lat: 37.629628,
          store_lng: 126.867185,
          business_hour: '10:30 ~ 20:30',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 12,
          user_id: 12,
          store_name: '동막골',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            ' 30년동안 이어져온 김막례 할머니의 손맛을 느낄수 있다! 그날 그날 가게주인의 마음에 따라 바뀌는 한국식 풀코스를 즐기실수 있는 한식 음식점 입니다. 매일 새벽 시장에서 신선한 재료들을 공수해서 조리합니다. 매일 매일 음식의 종류가 바뀝니다. ',
          store_address: '서울특별시 동작구 흑석동 210-3',
          store_category: '한식',
          store_lat: 37.505943,
          store_lng: 126.955334,
          business_hour: '11:00 ~ 23:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 13,
          user_id: 13,
          store_name: 'Un dîner delicieux',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '코슐랭 1성에 빛나는 1인 예약제 레스토랑 맛있는저녁(Un dîner delicieux) 입니다. 1인 예약제로 2시간 간격으로 운영되며 정통 프랑스식 코스요리를 즐기실수 있습니다. ',
          store_address: '서울특별시 송파구 송파1동 15-1',
          store_category: '양식',
          store_lat: 37.507876,
          store_lng: 127.1052,
          business_hour: '17:00 ~ 21:30',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 14,
          user_id: 14,
          store_name: '동경주방',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '일본식 커리와 가정식을 신도림 테크노마트 푸드코트에서 즐겨보세요! 저렴한 가격과 훌륭한 맛 둘다 잡은 인기 맛집! 동경주방입니다.  ',
          store_address: '구로동 3-25번지 신도림테크노마트 지하1층 FC동 06호 구로구 서울특별시 KR',
          store_category: '일식',
          store_lat: 37.507052,
          store_lng: 126.890279,
          business_hour: '11:00 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 15,
          user_id: 15,
          store_name: '황만식당',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '매콤한 제육볶음 부터 고등어조림 각종 한국식 백반을 맛볼수있는 황만식당입니다! 어머니의 손맛이 그리워질때 한번 방문해보세요~  ',
          store_address: '서울특별시 강남구 대치4동 935-11',
          store_category: '한식',
          store_lat: 37.498373,
          store_lng: 127.054925,
          business_hour: '11:00 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 16,
          user_id: 16,
          store_name: '틈새라면 천호점',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '명동 본점의 김복현 대표로부터 직접 배운 빨계떡 틈새라면의 천호점 입니다!. 끝장나는 매운맛의 본좌 빨계떡의 매력에 빠져 보세요 ',
          store_address: '서울특별시 강동구 천호3동 453-18',
          store_category: '분식',
          store_lat: 37.537996,
          store_lng: 127.127014,
          business_hour: '11:00 ~ 21:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 17,
          user_id: 17,
          store_name: '뽕따이 짬뽕',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            ' 3대를 이어온 완차이의 주방에서 배워온 20년경력의 주방장이 만드는 정통 중화요리 !! 요즘같이 추운 겨울날 시원 얼큰한 짬뽕 한그릇 어떠세요? ',
          store_address: '서울특별시 서대문구 신촌동 명물길 50-9',
          store_category: '중식',
          store_lat: 37.558687,
          store_lng: 126.939386,
          business_hour: '연중 무휴',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 18,
          user_id: 18,
          store_name: '창신동 매운 족발 본점',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '자극적이지 않고 맛있는 매운맛이 담겨있는 창신동 매운족발입니다. 부드러운 돼지고기와 매콤쫄깃한 족발의 환상의 조합이 기다리고있습니다!  ',
          store_address: '서울특별시 종로구 종로51길',
          store_category: '한식',
          store_lat: 37.572984,
          store_lng: 127.011529,
          business_hour: '15:00 ~ 24:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 19,
          user_id: 19,
          store_name: '초밥킹',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            ' 초밥의 본고장 일본 도쿄의 살몬구로(salmonguro)에서 배워온 참치와 연어초밥의 마스터 진현정 장인의 참치,연어 초밥 전문점입니다!. ',
          store_address: '서울특별시 마포구 마포대로10길',
          store_category: '일식',
          store_lat: 37.54712,
          store_lng: 126.954741,
          business_hour: '10:00 ~ 23:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 20,
          user_id: 20,
          store_name: '드림 버거하우스',
          store_image: 'client/src/img/dummy/원조할매국밥.png',
          store_order_quantity: '21',
          store_description:
            '최고급 소고기 목살과 갈빗살로 만든 패티에 체다와 모짜렐라 두가지 치즈의 환상적인 조합 신선한 토마토 양상추까지! 수제버거의 지존을 맛보실수있습니다.',
          store_address: '서울특별시 강남구 역삼1동 도곡로3길 26',
          store_category: '양식',
          store_lat: 37.49207,
          store_lng: 127.03282,
          business_hour: '연중 무휴',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 21,
          user_id: 21,
          store_name: '서초사리원',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 22,
          user_id: 22,
          store_name: '스시 다미선',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '일식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 23,
          user_id: 23,
          store_name: '강남정',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 24,
          user_id: 24,
          store_name: '서동한우 강남점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 25,
          user_id: 25,
          store_name: '모랑 강남점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 26,
          user_id: 26,
          store_name: '해우담 서초본점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 27,
          user_id: 27,
          store_name: '봉피양',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 28,
          user_id: 28,
          store_name: '더하누',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 29,
          user_id: 29,
          store_name: '강남역 기와집 양대창',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 30,
          user_id: 30,
          store_name: '진대감 강남역 삼성타운점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 31,
          user_id: 31,
          store_name: '됐소 강남',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 32,
          user_id: 32,
          store_name: '두껍삼 강남직영점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 33,
          user_id: 33,
          store_name: '초선과여포',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '중식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 34,
          user_id: 34,
          store_name: '삼성각',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '중식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 35,
          user_id: 35,
          store_name: '조선횟집 서초점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '일식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 36,
          user_id: 36,
          store_name: '한라담 강남역점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 37,
          user_id: 37,
          store_name: '진상샤브샤브',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 38,
          user_id: 38,
          store_name: '(주)미가미',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '일식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 39,
          user_id: 39,
          store_name: '삼호복집',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 40,
          user_id: 40,
          store_name: '만다린',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '중식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 41,
          user_id: 41,
          store_name: '참설농탕',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 42,
          user_id: 42,
          store_name: '남강메기 서초직영점',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 43,
          user_id: 43,
          store_name: '듬북담북(뱅뱅점)',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 44,
          user_id: 44,
          store_name: '서초버드나무집',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 45,
          user_id: 45,
          store_name: '육갑식당',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 46,
          user_id: 46,
          store_name: '한국수',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 47,
          user_id: 47,
          store_name: '춘향골 추어탕',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 48,
          user_id: 48,
          store_name: '오곡채',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 49,
          user_id: 49,
          store_name: '명선헌',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 50,
          user_id: 50,
          store_name: '김영자 원조 나주곰탕(서초점)',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 51,
          user_id: 51,
          store_name: '한촌설렁탕',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 52,
          user_id: 52,
          store_name: '황금빛 마을',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 53,
          user_id: 53,
          store_name: '서초복집',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 54,
          user_id: 54,
          store_name: '자인뭉티기',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 55,
          user_id: 55,
          store_name: '청정횟집',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '일식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 56,
          user_id: 56,
          store_name: '순남시래기',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 57,
          user_id: 57,
          store_name: '신가예촌',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 58,
          user_id: 58,
          store_name: '예촌',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 59,
          user_id: 59,
          store_name: '진주청국장',
          store_image: 'https://meal2sdk.s3.amazonaws.com/-001_12.jpg',
          store_order_quantity: randomIntFromInterval(1, 50),
          store_description: '',
          store_address: '',
          store_category: '한식',
          store_lat: (randomIntFromInterval(37450, 37570) / 1000).toFixed(3),
          store_lng: randomIntFromInterval(12690000, 12704000) / 100000,
          business_hour: '10:00 ~ 22:00',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('store', null, {});
  },
};
