const autoIncrement = () => {
  let n = 0;

  return function () {
    n++;
    return n;
  };
};

const autoIncrement2 = () => {
  let i = 0;

  return function () {
    i++;
    return i;
  };
};

const incrementer = autoIncrement2();

const cart_menu = [
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: autoIncrement()(),
    order_quantity: 3,
    cart_id: 1,
    menu_id: incrementer(),
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = cart_menu;
